name: ai_legal_chatbot
description: "A new Flutter project for the AI Legal Chatbot."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3 
  file_selector: ^0.8.0
  file_picker: ^8.0.0 
  cupertino_icons: ^1.0.8
  speech_to_text: ^5.6.1  # Add this for speech-to-text capabilities
  speech_to_text_platform_interface: ^2.3.0  # Ensure compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Corrected indentation for assets
  assets:
    - assets/images/constitution_page.jpg
    - assets/images/constitution_bg.jpg

  # Fonts (uncomment and configure if you need custom fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
